version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      time: '00:00'
      interval: 'daily'
      timezone: 'Europe/Tallinn'
    open-pull-requests-limit: 50
    labels:
      - 'dependencies'
    pull-request-branch-name:
      separator: '/'
    ignore:
      - dependency-name: '@types/node'
